on:
  push:
    branches:
      - master

jobs:
  generate_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '14.x'
      - name: checkout
        uses: actions/checkout@v2.3.2
      - name: install
        run: npm install
